### ISSUE TITLE
doesn't work on Ubuntu 14

### ISSUE THREAD

**Issue by keithbriggs** [I3ck/lib_2d#1] opened 2016-01-08 11:38 UTC
kbriggs:~/Downloads/lib_2d-master> make tests
mkdir -p bin/
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_DOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_DOUBLE
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_LDOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_LDOUBLE
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_FLOAT tests/test_lib_2d.cpp -o bin/test_lib_2d_FLOAT
./bin/test_lib_2d_DOUBLE
make: **\* [run_tests] Segmentation fault (core dumped)

**Comment by I3ck** [comment] 2016-01-08 16:43
Can reproduce this with the long double version on my machine.

Seems like the change 2015-02-01  17:02 introduced the bug.

I guess I'll get it fixed this weekend.

Since it is only broken for long double on my machine, you could try running the float or long double executeable, maybe it works for you there (your run of the double version fails and therefore the others are never executed)

**Comment by keithbriggs** [comment] 2016-01-08 17:07
Thanks for the reply - all tests crash.

Keith

kbriggs:~/Downloads/lib_2d-master> make
mkdir -p bin/
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_DOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_DOUBLE
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_LDOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_LDOUBLE
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_FLOAT tests/test_lib_2d.cpp -o bin/test_lib_2d_FLOAT
./bin/test_lib_2d_DOUBLE
make: **\* [run_tests] Segmentation fault (core dumped)
kbriggs:~/Downloads/lib_2d-master> bin/test_lib_2d_LDOUBLE
Segmentation fault (core dumped)
kbriggs:~/Downloads/lib_2d-master> bin/test_lib_2d_FLOAT
Segmentation fault (core dumped)
kbriggs:~/Downloads/lib_2d-master> bin/test_lib_2d_DOUBLE
Segmentation fault (core dumped)

Please note:

kbriggs:~/Downloads/lib_2d-master> g++ -Wall -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_DOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_DOUBLE
In file included from tests/../lib_2d.h:32:0,
                 from tests/test_lib_2d.cpp:26:
tests/../inc/KdTree.h: In instantiation of 'lib_2d::KdTree<T>::KdTree(std::shared_ptr<lib_2d::OrderedPointCloud<T> >, int) [with T = double]':
tests/test_lib_2d.cpp:800:26:   required from here
tests/../inc/KdTree.h:57:15: warning: 'lib_2d::KdTree<double>::dimension' will be initialized after [-Wreorder]
     const int dimension;
               ^
tests/../inc/KdTree.h:55:43: warning:   'std::shared_ptr<lib_2d::OrderedPointCloud<double> > lib_2d::KdTree<double>::parent' [-Wreorder]
     std::shared_ptr<OrderedPointCloud<T>> parent;
                                           ^
tests/../inc/KdTree.h:67:5: warning:   when initialized here [-Wreorder]
     KdTree(std::shared_ptr<OrderedPointCloud<T>> tpc, int dim = 0) :

**Comment by I3ck** [comment] 2016-01-08 17:14
Could you try it again with the current version? (after https://github.com/I3ck/lib_2d/commit/845c0aa2261c81294cde923b7bea9160047e7ccc )

**Comment by keithbriggs** [comment] 2016-01-09 09:15
Yes - that seems ok.  Thanks for the fix - but the compiler warnings are still present.

Keith

kbriggs:~/Downloads/lib_2d-master> make
mkdir -p bin/
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_DOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_DOUBLE
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_LDOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_LDOUBLE
g++ -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_FLOAT tests/test_lib_2d.cpp -o bin/test_lib_2d_FLOAT

# ./bin/test_lib_2d_DOUBLE

All tests passed (161 assertions in 11 test cases)

# ./bin/test_lib_2d_LDOUBLE

All tests passed (161 assertions in 11 test cases)

# ./bin/test_lib_2d_FLOAT

All tests passed (161 assertions in 11 test cases)

kbriggs:~/Downloads/lib_2d-master> g++ -Wall -std=c++11 -fmax-errors=10 -DNDEBUG -D USE_DOUBLE tests/test_lib_2d.cpp -o bin/test_lib_2d_DOUBLE
In file included from tests/../lib_2d.h:32:0,
                 from tests/test_lib_2d.cpp:26:
tests/../inc/KdTree.h: In instantiation of 'lib_2d::KdTree<T>::KdTree(std::shared_ptr<lib_2d::OrderedPointCloud<T> >, int) [with T = double]':
tests/test_lib_2d.cpp:800:26:   required from here
tests/../inc/KdTree.h:57:15: warning: 'lib_2d::KdTree<double>::dimension' will be initialized after [-Wreorder]
     const int dimension;
               ^
tests/../inc/KdTree.h:55:43: warning:   'std::shared_ptr<lib_2d::OrderedPointCloud<double> > lib_2d::KdTree<double>::parent' [-Wreorder]
     std::shared_ptr<OrderedPointCloud<T>> parent;
                                           ^
tests/../inc/KdTree.h:67:5: warning:   when initialized here [-Wreorder]
     KdTree(std::shared_ptr<OrderedPointCloud<T>> tpc, int dim = 0) :

**Comment by I3ck** [comment] 2016-01-09 11:28
I'll close this issue, add warning flags and resolve these aswell. Thank you for your feedback and good luck with your project

**Closed as completed by I3ck** 2016-01-09 11:28 UTC

**Comment by I3ck** [comment] 2016-01-09 12:10
warnings are now all enabled and treated as errors. Also resolved them
